CREATE TABLE member(
userId VARCHAR(30) NOT NULL,
userPw VARCHAR(100) NOT NULL,
userNo INT PRIMARY KEY AUTO_INCREMENT,
userNickname VARCHAR(30) NOT NULL,
userGender VARCHAR(2) NOT NULL,
userAge INT(3) NOT NULL,
userMail VARCHAR(30) NOT NULL,
regDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
unique(userNickname)
);